list = [
        {
            "createBy": "admin",
            "createTime": "2026-04-14 20:55:41",
            "params": {},
            "deptId": 100,
            "parentId": 0,
            "ancestors": "0",
            "deptName": "若依科技",
            "orderNum": "0",
            "leader": "若依",
            "phone": "15888888888",
            "email": "ry@qq.com",
            "status": "0",
            "delFlag": "0",
            "children": []
        },
        {
            "createBy": "admin",
            "createTime": "2026-04-14 20:55:41",
            "params": {},
            "deptId": 101,
            "parentId": 100,
            "ancestors": "0,100",
            "deptName": "深圳总公司",
            "orderNum": "1",
            "leader": "若依",
            "phone": "15888888887",
            "email": "ry@qq.com",
            "status": "0",
            "delFlag": "0",
            "children": []
        },
        {

            "createBy": "admin",
            "createTime": "2026-04-14 20:55:41",
            "params": {},
            "deptId": 102,
            "parentId": 100,
            "ancestors": "0,100",
            "deptName": "长沙分公司",
            "orderNum": "2",
            "leader": "若依",
            "phone": "15888888888",
            "email": "ry@qq.com",
            "status": "0",
            "delFlag": "0",
            "children": []
        },
        {
            "createBy": "admin",
            "createTime": "2026-04-14 20:55:41",
            "params": {},
            "deptId": 103,
            "parentId": 101,
            "ancestors": "0,100,101",
            "deptName": "研发部门",
            "orderNum": "1",
            "leader": "若依",
            "phone": "15888888888",
            "email": "ry@qq.com",
            "status": "0",
            "delFlag": "0",
            "children": []
        },
        {
            "createBy": "admin",
            "createTime": "2026-04-14 20:55:41",
            "params": {},
            "deptId": 106,
            "parentId": 101,
            "ancestors": "0,100,101",
            "deptName": "财务部门",
            "orderNum": "4",
            "leader": "若依",
            "phone": "15888888888",
            "email": "ry@qq.com",
            "status": "0",
            "delFlag": "0",
            "children": []
        },
        {
            "createBy": "admin",
            "createTime": "2026-04-14 20:55:41",
            "params": {},
            "deptId": 107,
            "parentId": 101,
            "ancestors": "0,100,101",
            "deptName": "运维部门",
            "orderNum": "5",
            "leader": "若依",
            "phone": "15888888888",
            "email": "ry@qq.com",
            "status": "0",
            "delFlag": "0",
            "children": []
        },
        {
            "createBy": "admin",
            "createTime": "2026-04-14 20:55:41",
            "params": {},
            "deptId": 108,
            "parentId": 102,
            "ancestors": "0,100,102",
            "deptName": "市场部门",
            "orderNum": "1",
            "leader": "若依",
            "phone": "15888888888",
            "email": "ry@qq.com",
            "status": "0",
            "delFlag": "0",
            "children": []
        },
        {
            "createBy": "admin",
            "createTime": "2026-04-14 20:55:41",
            "params": {},
            "deptId": 109,
            "parentId": 102,
            "ancestors": "0,100,102",
            "deptName": "财务部门",
            "orderNum": "2",
            "leader": "若依",
            "phone": "15888888888",
            "email": "ry@qq.com",
            "status": "0",
            "delFlag": "0",
            "children": []
        }
    ]
for dict in list:
    assert dict.get("status") == "0"
